$scheme_get_survey_by_id = {type: 'object',
                            properties: {_id: {type: 'String'},
                                         audience: {type: 'Integer'},
                                         state: {type: 'Integer'},
                                         creationDate: {type: 'String'},
                                         description: {type: 'String'},
                                         releaseDate_id: {type: 'String'},
                                         responseQuantity: {type: 'Integer'},
                                         title: {type: 'String'},
                                         owner: {type: 'String'},
                                         __v: {type: 'Integer'},
                                         questions: {type: []},
                                         domain: {type: []}}}
