$scheme_get_user_by_id = {type: 'object',
                          properties: {_id: {type: 'String'},
                                       audience: {type: 'Integer'},
                                       creationDate: {type: 'String'},
                                       description: {type: 'String'},
                                       expirationDate: {type: 'String'},
                                       releaseDate: {type: 'String'},
                                       responseQuantity: {type: 'Integer'},
                                       state: {type: 'Integer'},
                                       title: {type: 'String'},
                                       owner: {type: 'String'},
                                       __v: {type: 'Integer'},
                                       questions: {type: []},
                                       domains: {type: []}}}