$scheme_post_survey = {type: 'object',
                       properties: {__v: {type: 'Integer'},
                                    title: {type: 'String'},
                                    description: {type: 'String'},
                                    audience: {type: 'Integer'},
                                    state: {type: 'Integer'},
                                    releaseDate: {type: 'String'},
                                    creationDate: {type: 'String'},
                                    expirationDate: {type: 'String'},
                                    responseQuantity: {type: 'Integer'},
                                    owner: {type: 'String'},
                                    _id: {type: 'String'},
                                    questions: {type: []},
                                    domains: {type: []}}}
