$scheme_post_user_email = {type: 'object',
                           properties: {_id: {type: 'String'},
                                        name: {type: 'String'},
                                        primaryEmail: {type: 'String'},
                                        password: {type: 'String'},
                                        birthDate: {type: 'Boolean'},
                                        validated: {type: 'String'},
                                        city: {type: 'String'},
                                        country: {type: 'String'},
                                        gender: {type: 'String'},
                                        role: {type: 'String'},
                                        __v: {type: 'String'},
                                        secondaryEmails: {email: {type: 'String'},
                                                          validated: {type: 'Boolean'},
                                                          _id: {type: 'String'}}}}
                                                         