$scheme_post_survey_state = {type: 'object',
                             properties: {_id: {type: 'String'},
                                          audience: {type: 'Integer'},
                                          creationDate: {type: 'String'},
                                          description: {type: 'String'},
                                          expirationDate: {type: 'String'},
                                          releaseDate: {type: 'String'},
                                          responseQuantity: {type: 'Integer'},
                                          state: {type: 'Integer'},
                                          title: {type: 'String'},
                                          owner: {type: 'String'},
                                          __v: {type: 'Integer'},
                                          questions: {type: []},
                                          domains: {type: []}}}
