# Custom config for Rubocop
Style/GlobalVars:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 35

Metrics/MethodLength:
  Max: 15

AllCops:
  Exclude:
    - './features/support/json_scheme_templates/**'
