require_relative './load_schema_files.rb'
$variables_schema = {}
$variables_schema.store('delete_survey', $scheme_delete_survey)
$variables_schema.store('get_health', $scheme_get_health)
$variables_schema.store('get_survey_by_id', $scheme_get_survey_by_id)
$variables_schema.store('get_survey_overview', $scheme_get_survey_overview)
$variables_schema.store('get_survey_stats_with_questions', $scheme_get_survey_stats_with_q)
$variables_schema.store('get_survey_stats_without_questions', $scheme_get_survey_stats_without)
$variables_schema.store('get_surveys', $scheme_get_surveys)
$variables_schema.store('get_survey_results_csv', $scheme_get_survey_results_csv)
$variables_schema.store('get_surveys_results_json', $scheme_get_surveys_results_json)
$variables_schema.store('get_user_by_id', $scheme_get_user_by_id)
$variables_schema.store('scheme_post_login ',$scheme_post_login)
$variables_schema.store('post_logout ', $Scheme_post_logout)
$variables_schema.store('post_survey', $scheme_post_survey)
$variables_schema.store('post_survey_clone', $scheme_post_survey_clone)
$variables_schema.store('post_user_email', $scheme_post_user_email)
$variables_schema.store('post_survey_state', $scheme_post_survey_state)
$variables_schema.store('post_surveys_answers', $scheme_post_surveys_answers)
$variables_schema.store('post_token', $scheme_post_token)
$variables_schema.store('user_creation', $scheme_user_creation)
$variables_schema.store('user_login', $scheme_user_login)
